-- AlterTable
ALTER TABLE `admissions` ADD COLUMN `addressCity` VARCHAR(191) NULL,
    ADD COLUMN `addressPincode` VARCHAR(191) NULL,
    ADD COLUMN `addressState` VARCHAR(191) NULL,
    ADD COLUMN `addressStreet` VARCHAR(191) NULL,
    ADD COLUMN `admissionSource` VARCHAR(191) NULL,
    ADD COLUMN `allergies` VARCHAR(191) NULL,
    ADD COLUMN `birthCertificateDoc` VARCHAR(191) NULL,
    ADD COLUMN `bloodGroup` VARCHAR(191) NULL,
    ADD COLUMN `category` VARCHAR(191) NULL,
    ADD COLUMN `emergencyContactName` VARCHAR(191) NULL,
    ADD COLUMN `emergencyContactPhone` VARCHAR(191) NULL,
    ADD COLUMN `fatherAadhaar` VARCHAR(191) NULL,
    ADD COLUMN `fatherAnnualIncome` DOUBLE NULL,
    ADD COLUMN `fatherEmail` VARCHAR(191) NULL,
    ADD COLUMN `fatherOccupation` VARCHAR(191) NULL,
    ADD COLUMN `fatherOfficeAddress` VARCHAR(191) NULL,
    ADD COLUMN `fatherQualification` VARCHAR(191) NULL,
    ADD COLUMN `guardianAddress` VARCHAR(191) NULL,
    ADD COLUMN `guardianOccupation` VARCHAR(191) NULL,
    ADD COLUMN `guardianRelationship` VARCHAR(191) NULL,
    ADD COLUMN `hostelRequired` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `lastClassAttended` VARCHAR(191) NULL,
    ADD COLUMN `medicalCondition` VARCHAR(191) NULL,
    ADD COLUMN `middleName` VARCHAR(191) NULL,
    ADD COLUMN `motherAadhaar` VARCHAR(191) NULL,
    ADD COLUMN `motherAnnualIncome` DOUBLE NULL,
    ADD COLUMN `motherEmail` VARCHAR(191) NULL,
    ADD COLUMN `motherOccupation` VARCHAR(191) NULL,
    ADD COLUMN `motherOfficeAddress` VARCHAR(191) NULL,
    ADD COLUMN `motherQualification` VARCHAR(191) NULL,
    ADD COLUMN `motherTongue` VARCHAR(191) NULL,
    ADD COLUMN `nationality` VARCHAR(191) NULL DEFAULT 'Indian',
    ADD COLUMN `parentAadhaarDoc` VARCHAR(191) NULL,
    ADD COLUMN `permanentAddressCity` VARCHAR(191) NULL,
    ADD COLUMN `permanentAddressPincode` VARCHAR(191) NULL,
    ADD COLUMN `permanentAddressState` VARCHAR(191) NULL,
    ADD COLUMN `permanentAddressStreet` VARCHAR(191) NULL,
    ADD COLUMN `previousBoard` VARCHAR(191) NULL,
    ADD COLUMN `previousMarks` DOUBLE NULL,
    ADD COLUMN `previousMarksCardDoc` VARCHAR(191) NULL,
    ADD COLUMN `religion` VARCHAR(191) NULL,
    ADD COLUMN `specialNeeds` VARCHAR(191) NULL,
    ADD COLUMN `studentAadhaarDoc` VARCHAR(191) NULL,
    ADD COLUMN `studentPhoto` VARCHAR(191) NULL,
    ADD COLUMN `transferCertificateDoc` VARCHAR(191) NULL,
    ADD COLUMN `transferCertificateNo` VARCHAR(191) NULL,
    ADD COLUMN `transportRequired` BOOLEAN NULL DEFAULT false;
